// <auto-generated />
using System;
using CoreCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCrud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180912211744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("CoreCrud.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("CoreCrud.Models.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<bool>("IsAnalog");

                    b.Property<DateTime>("LaunchDate");

                    b.Property<int>("ManufacturerId");

                    b.Property<string>("Material");

                    b.Property<decimal>("Price");

                    b.Property<int?>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Watch");
                });

            modelBuilder.Entity("CoreCrud.Models.Watch", b =>
                {
                    b.HasOne("CoreCrud.Models.Manufacturer", "Manufacturer")
                        .WithMany("Watch")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
